package gogen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	goparser "go/parser"
	"go/token"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/dave/jennifer/jen"
	"github.com/norunners/tue/internal/compiler/script"
	"github.com/norunners/tue/internal/compiler/sfc"
	gotemplate "github.com/norunners/tue/internal/compiler/template"
)

const tueImportPath = "github.com/norunners/tue"

// GenerateProject generates cache files for a parsed project.
func GenerateProject(project Project) (*Result, []Diagnostic) {
	generator := projectGenerator{
		manifest: Manifest{GeneratedBy: "tue"},
	}
	generator.generate(project)
	if len(generator.diagnostics) != 0 {
		return nil, generator.diagnostics
	}
	return &Result{
		Files:    generator.files,
		Manifest: generator.manifest,
	}, nil
}

type projectGenerator struct {
	packageName string
	components  map[string]componentBinding
	files       []GeneratedFile
	manifest    Manifest
	diagnostics []Diagnostic
}

func (g *projectGenerator) generate(project Project) {
	g.indexComponents(project.Files)
	if len(g.diagnostics) != 0 {
		return
	}
	for _, file := range project.Files {
		g.generateFile(file)
	}
}

type componentBinding struct {
	path      string
	component *script.Component
	props     map[string]script.Prop
}

func (g *projectGenerator) indexComponents(files []File) {
	g.components = make(map[string]componentBinding, len(files))
	for _, file := range files {
		path := filePath(file)
		if file.Script == nil || file.Script.Component == nil {
			continue
		}

		component := file.Script.Component
		if previous, ok := g.components[component.Name]; ok {
			g.add(path, fmt.Sprintf("duplicate component %q; first declared in %s", component.Name, previous.path), component.NameSpan)
			continue
		}

		props := make(map[string]script.Prop, len(component.Props))
		for _, prop := range component.Props {
			props[prop.Name] = prop
		}
		g.components[component.Name] = componentBinding{
			path:      path,
			component: component,
			props:     props,
		}
	}
}

func (g *projectGenerator) generateFile(file File) {
	path := filePath(file)
	if file.Template == nil {
		g.add(path, "missing parsed template", sfc.Span{})
		return
	}
	if file.Script == nil || file.Script.Component == nil {
		g.add(path, "missing component contract", file.Template.Span)
		return
	}
	if file.Script.PackageName == "" {
		g.add(path, "missing script package name", file.Template.Span)
		return
	}
	if g.packageName == "" {
		g.packageName = file.Script.PackageName
	} else if file.Script.PackageName != g.packageName {
		g.add(path, fmt.Sprintf("generated cache supports one package, got %q after %q", file.Script.PackageName, g.packageName), file.Script.PackageSpan)
		return
	}

	stem := generatedStem(path)
	scriptPath := stem + "_tue.go"
	renderPath := stem + "_render_tue.go"

	scriptSource, ok := g.generatedScriptSource(file)
	if !ok {
		return
	}
	renderSource, nodes, ok := g.generatedRenderSource(file)
	if !ok {
		return
	}

	g.files = append(g.files,
		GeneratedFile{Path: scriptPath, Source: scriptSource},
		GeneratedFile{Path: renderPath, Source: renderSource},
	)
	g.manifest.Files = append(g.manifest.Files, ManifestFile{
		Source:     path,
		Component:  file.Script.Component.Name,
		ScriptFile: scriptPath,
		RenderFile: renderPath,
		Nodes:      nodes,
	})
}

func (g *projectGenerator) generatedScriptSource(file File) ([]byte, bool) {
	source := strings.TrimSpace(file.ScriptSource)
	if source == "" {
		g.add(filePath(file), "missing script source", file.Template.Span)
		return nil, false
	}

	generated := []byte("// Code generated by tue; DO NOT EDIT.\n\n" + source + "\n")
	formatted, err := format.Source(generated)
	if err != nil {
		g.add(filePath(file), fmt.Sprintf("format generated script: %v", err), file.Script.PackageSpan)
		return nil, false
	}
	return formatted, true
}

func (g *projectGenerator) generatedRenderSource(file File) ([]byte, []ManifestNode, bool) {
	renderer := fileGenerator{
		path:       filePath(file),
		file:       jen.NewFile(file.Script.PackageName),
		component:  file.Script.Component,
		components: g.components,
		fields:     componentFields(file.Script.Component),
		methods:    componentMethods(file.Script.Component),
	}
	renderer.file.HeaderComment("Code generated by tue; DO NOT EDIT.")
	renderer.file.ImportName(tueImportPath, "tue")
	renderer.file.ImportName("fmt", "fmt")
	renderer.generate(file.Template)
	if len(renderer.diagnostics) != 0 {
		g.diagnostics = append(g.diagnostics, renderer.diagnostics...)
		return nil, nil, false
	}

	source, err := renderJenniferFile(renderer.file)
	if err != nil {
		g.add(filePath(file), fmt.Sprintf("render generated Go: %v", err), file.Script.Component.NameSpan)
		return nil, nil, false
	}
	return source, renderer.nodes, true
}

type fileGenerator struct {
	path        string
	file        *jen.File
	component   *script.Component
	components  map[string]componentBinding
	fields      map[string]script.Field
	methods     map[string]script.Method
	nodes       []ManifestNode
	diagnostics []Diagnostic
}

func (g *fileGenerator) generate(tree *gotemplate.Tree) {
	componentName := g.component.Name
	g.file.Func().Id("New"+componentName).Params().Op("*").Qual(tueImportPath, "Comp").Block(
		jen.Id("component").Op(":=").Op("&").Id(componentName).Values(),
		jen.Return(jen.Qual(tueImportPath, "CompOf").Call(jen.Id("component"), jen.Id("render"+componentName))),
	)
	g.file.Line()
	g.file.Func().Id("render"+componentName).Params(jen.Id("component").Op("*").Id(componentName)).Qual(tueImportPath, "VNode").Block(
		jen.Return(g.renderNodes(tree.Nodes)),
	)
}

func (g *fileGenerator) renderNodes(nodes []*gotemplate.Node) jen.Code {
	rendered := make([]jen.Code, 0, len(nodes))
	for _, node := range nodes {
		if code, ok := g.renderNode(node); ok {
			rendered = append(rendered, code)
		}
	}
	if len(rendered) == 1 {
		return rendered[0]
	}
	return jen.Qual(tueImportPath, "Fragment").Call(g.vnodeSlice(rendered))
}

func (g *fileGenerator) renderNode(node *gotemplate.Node) (jen.Code, bool) {
	if node == nil {
		return nil, false
	}

	switch node.Kind {
	case gotemplate.NodeElement:
		return g.renderElement(node)
	case gotemplate.NodeText:
		if strings.TrimSpace(node.Text) == "" {
			return nil, false
		}
		g.recordNode(node)
		return jen.Qual(tueImportPath, "Text").Call(jen.Lit(node.Text)), true
	case gotemplate.NodeInterpolation:
		return g.renderInterpolation(node)
	case gotemplate.NodeComment:
		return nil, false
	default:
		g.add(fmt.Sprintf("unsupported template node kind %q", node.Kind), node.Span)
		return nil, false
	}
}

func (g *fileGenerator) renderElement(node *gotemplate.Node) (jen.Code, bool) {
	if node.IsComponent {
		return g.renderComponent(node)
	}

	attrs, events, ok := g.renderAttrsAndEvents(node)
	if !ok {
		return nil, false
	}

	children := make([]jen.Code, 0, len(node.Children))
	for _, child := range node.Children {
		childCode, ok := g.renderNode(child)
		if ok {
			children = append(children, childCode)
		}
	}

	g.recordNode(node)
	if len(events) != 0 {
		return jen.Qual(tueImportPath, "ElementWithEvents").Call(
			jen.Lit(node.Tag),
			g.attributeSlice(attrs),
			g.eventSlice(events),
			g.vnodeSlice(children),
		), true
	}
	return jen.Qual(tueImportPath, "Element").Call(
		jen.Lit(node.Tag),
		g.attributeSlice(attrs),
		g.vnodeSlice(children),
	), true
}

func (g *fileGenerator) renderComponent(node *gotemplate.Node) (jen.Code, bool) {
	child, ok := g.components[node.Tag]
	if !ok {
		g.add(fmt.Sprintf("component %q is not registered", node.Tag), node.TagSpan)
		return nil, false
	}
	if hasRenderableComponentChildren(node.Children) {
		g.add(fmt.Sprintf("component %q children generation is not supported in the component render slice", node.Tag), node.ContentSpan)
		return nil, false
	}

	fields, ok := g.renderComponentPropFields(node, child)
	if !ok {
		return nil, false
	}

	g.recordNode(node)
	return jen.Qual(tueImportPath, "Component").Call(
		jen.Lit(node.Tag),
		jen.Func().Params().Op("*").Qual(tueImportPath, "Comp").Block(
			jen.Id("child").Op(":=").Op("&").Id(child.component.Name).Values(fields...),
			jen.Return(jen.Qual(tueImportPath, "CompOf").Call(jen.Id("child"), jen.Id("render"+child.component.Name))),
		),
	), true
}

func (g *fileGenerator) renderComponentPropFields(node *gotemplate.Node, child componentBinding) ([]jen.Code, bool) {
	values := make(map[string]jen.Code, len(node.Attrs))
	ok := true
	for _, attr := range node.Attrs {
		switch attr.Kind {
		case gotemplate.AttrStatic:
			prop, found := child.props[attr.Name]
			if !found {
				g.add(fmt.Sprintf("component %q has no prop %q", node.Tag, attr.Name), attr.NameSpan)
				ok = false
				continue
			}
			value, valueOK := g.renderStaticComponentProp(node.Tag, prop, attr)
			if !valueOK {
				ok = false
				continue
			}
			values[prop.Name] = value
		case gotemplate.AttrBind:
			prop, found := child.props[attr.Argument]
			if !found {
				g.add(fmt.Sprintf("component %q has no prop %q", node.Tag, attr.Argument), attr.ArgumentSpan)
				ok = false
				continue
			}
			value, valueOK := g.renderBoundComponentProp(prop, attr)
			if !valueOK {
				ok = false
				continue
			}
			values[prop.Name] = value
		case gotemplate.AttrEvent:
			g.add(fmt.Sprintf("component event attribute %q generation is not supported in the component render slice", attr.RawName), attr.Span)
			ok = false
		case gotemplate.AttrDirective:
			g.add(fmt.Sprintf("directive %q generation is not supported on components in the component render slice", attr.RawName), attr.Span)
			ok = false
		default:
			g.add(fmt.Sprintf("unsupported component attribute kind %q", attr.Kind), attr.Span)
			ok = false
		}
	}

	fields := make([]jen.Code, 0, len(child.component.Props))
	for _, prop := range child.component.Props {
		value, found := values[prop.Name]
		if !found {
			if prop.Required {
				g.add(fmt.Sprintf("component %q requires prop %q", node.Tag, prop.Name), node.TagSpan)
				ok = false
				continue
			}
			zero, zeroOK := zeroPropValue(prop)
			if !zeroOK {
				g.add(fmt.Sprintf("component %q prop %q has unsupported type %q", node.Tag, prop.Name, propValueType(prop)), prop.Field.TypeSpan)
				ok = false
				continue
			}
			value = zero
		}
		fields = append(fields, jen.Id(prop.Field.Name).Op(":").Add(value))
	}
	return fields, ok
}

func (g *fileGenerator) renderStaticComponentProp(componentName string, prop script.Prop, attr gotemplate.Attr) (jen.Code, bool) {
	expected := propValueType(prop)
	actual := "string"
	span := attr.ValueSpan
	if !attr.HasValue {
		actual = "bool"
		span = attr.NameSpan
	}
	if !assignableType(expected, actual) {
		g.add(
			fmt.Sprintf("component %q prop %q expects %s, got %s", componentName, prop.Name, displayType(expected), displayType(actual)),
			span,
		)
		return nil, false
	}
	if !attr.HasValue {
		return jen.Qual(tueImportPath, "PropOf").Call(jen.True()), true
	}
	return jen.Qual(tueImportPath, "PropOf").Call(jen.Lit(attr.Value)), true
}

func (g *fileGenerator) renderBoundComponentProp(prop script.Prop, attr gotemplate.Attr) (jen.Code, bool) {
	expression, ok := g.renderExpression(attr.Expression, attr.ExpressionSpan)
	if !ok {
		return nil, false
	}
	valueType, ok := renderTypeExpression(propValueType(prop))
	if !ok {
		g.add(fmt.Sprintf("component prop %q has unsupported type %q", prop.Name, propValueType(prop)), prop.Field.TypeSpan)
		return nil, false
	}
	return jen.Qual(tueImportPath, "PropOfFunc").Call(
		jen.Func().Params().Add(valueType).Block(jen.Return(expression)),
	), true
}

func (g *fileGenerator) renderAttrsAndEvents(node *gotemplate.Node) ([]jen.Code, []jen.Code, bool) {
	attrs := make([]jen.Code, 0, len(node.Attrs))
	events := make([]jen.Code, 0, len(node.Attrs))
	ok := true
	for _, attr := range node.Attrs {
		switch attr.Kind {
		case gotemplate.AttrStatic:
			if attr.HasValue {
				attrs = append(attrs, jen.Qual(tueImportPath, "Attr").Call(jen.Lit(attr.Name), jen.Lit(attr.Value)))
			} else {
				attrs = append(attrs, jen.Qual(tueImportPath, "BoolAttr").Call(jen.Lit(attr.Name)))
			}
		case gotemplate.AttrBind:
			g.add(fmt.Sprintf("bound attribute %q generation is not supported in the static render slice", attr.RawName), attr.Span)
			ok = false
		case gotemplate.AttrEvent:
			event, eventOK := g.renderEvent(attr)
			if !eventOK {
				ok = false
				continue
			}
			events = append(events, event)
		case gotemplate.AttrDirective:
			g.add(fmt.Sprintf("directive %q generation is not supported in the static render slice", attr.RawName), attr.Span)
			ok = false
		default:
			g.add(fmt.Sprintf("unsupported attribute kind %q", attr.Kind), attr.Span)
			ok = false
		}
	}
	return attrs, events, ok
}

func (g *fileGenerator) renderEvent(attr gotemplate.Attr) (jen.Code, bool) {
	methodName, callWithArgs, ok := g.eventHandlerMethod(attr)
	if !ok {
		return nil, false
	}
	if callWithArgs {
		g.add(fmt.Sprintf("event handler %q does not accept arguments", methodName), attr.ExpressionSpan)
		return nil, false
	}

	method, ok := g.methods[methodName]
	if !ok {
		g.add(fmt.Sprintf("event handler %q is not a method on %s", methodName, g.component.Name), attr.ExpressionSpan)
		return nil, false
	}
	if len(method.Parameters) != 0 || len(method.Results) != 0 {
		g.add(fmt.Sprintf("event handler %q must have signature func()", methodName), attr.ExpressionSpan)
		return nil, false
	}

	return jen.Qual(tueImportPath, "On").Call(
		jen.Lit(attr.Argument),
		jen.Id("component").Dot(methodName),
	), true
}

func (g *fileGenerator) eventHandlerMethod(attr gotemplate.Attr) (string, bool, bool) {
	expr, err := goparser.ParseExprFrom(token.NewFileSet(), "", attr.Expression, 0)
	if err != nil {
		g.add(fmt.Sprintf("invalid event handler expression: %s", err), attr.ExpressionSpan)
		return "", false, false
	}

	switch typed := expr.(type) {
	case *ast.Ident:
		return typed.Name, false, true
	case *ast.CallExpr:
		ident, ok := typed.Fun.(*ast.Ident)
		if !ok {
			g.add("event handler generation supports component method calls only", attr.ExpressionSpan)
			return "", false, false
		}
		return ident.Name, len(typed.Args) != 0, true
	default:
		g.add("event handler generation supports component methods only", attr.ExpressionSpan)
		return "", false, false
	}
}

func (g *fileGenerator) renderInterpolation(node *gotemplate.Node) (jen.Code, bool) {
	expression, ok := g.renderExpression(node.Expression, node.ExpressionSpan)
	if !ok {
		return nil, false
	}
	g.recordNode(node)
	return jen.Qual(tueImportPath, "Text").Call(jen.Qual("fmt", "Sprint").Call(expression)), true
}

func (g *fileGenerator) renderExpression(expression string, span sfc.Span) (jen.Code, bool) {
	expr, err := goparser.ParseExprFrom(token.NewFileSet(), "", expression, 0)
	if err != nil {
		g.add(fmt.Sprintf("invalid interpolation expression: %s", err), span)
		return nil, false
	}

	generated := expressionGenerator{
		fields: g.fields,
	}
	code, ok := generated.render(expr)
	if !ok {
		g.add("interpolation expression is not supported in the static render slice", span)
		return nil, false
	}
	return code, true
}

func (g *fileGenerator) attributeSlice(attrs []jen.Code) jen.Code {
	if len(attrs) == 0 {
		return jen.Nil()
	}
	return jen.Index().Qual(tueImportPath, "Attribute").Values(attrs...)
}

func (g *fileGenerator) eventSlice(events []jen.Code) jen.Code {
	if len(events) == 0 {
		return jen.Nil()
	}
	return jen.Index().Qual(tueImportPath, "EventBinding").Values(events...)
}

func (g *fileGenerator) vnodeSlice(nodes []jen.Code) jen.Code {
	if len(nodes) == 0 {
		return jen.Nil()
	}
	return jen.Index().Qual(tueImportPath, "VNode").Values(nodes...)
}

func (g *fileGenerator) recordNode(node *gotemplate.Node) {
	manifestNode := ManifestNode{
		Kind:       string(node.Kind),
		Tag:        node.Tag,
		SourceSpan: node.Span,
	}
	g.nodes = append(g.nodes, manifestNode)
}

func (g *fileGenerator) add(message string, span sfc.Span) {
	g.diagnostics = append(g.diagnostics, Diagnostic{
		Path:    g.path,
		Message: message,
		Span:    span,
	})
}

func (g *projectGenerator) add(path string, message string, span sfc.Span) {
	g.diagnostics = append(g.diagnostics, Diagnostic{
		Path:    path,
		Message: message,
		Span:    span,
	})
}

func renderJenniferFile(file *jen.File) ([]byte, error) {
	var buffer bytes.Buffer
	if err := file.Render(&buffer); err != nil {
		return nil, err
	}
	return format.Source(buffer.Bytes())
}

func componentFields(component *script.Component) map[string]script.Field {
	fields := make(map[string]script.Field)
	for _, prop := range component.Props {
		fields[prop.Field.Name] = prop.Field
	}
	for _, field := range component.State {
		fields[field.Name] = field
	}
	for _, field := range component.Refs {
		fields[field.Name] = field
	}
	for _, field := range component.Computed {
		fields[field.Name] = field
	}
	for _, field := range component.Resources {
		fields[field.Name] = field
	}
	return fields
}

func componentMethods(component *script.Component) map[string]script.Method {
	methods := make(map[string]script.Method)
	if component == nil {
		return methods
	}
	for _, method := range component.Methods {
		methods[method.Name] = method
	}
	return methods
}

func propValueType(prop script.Prop) string {
	if prop.Field.ValueType != "" {
		return prop.Field.ValueType
	}
	return prop.Field.Type
}

func zeroPropValue(prop script.Prop) (jen.Code, bool) {
	valueType := propValueType(prop)
	switch normalizeType(valueType) {
	case "string":
		return jen.Qual(tueImportPath, "PropOf").Call(jen.Lit("")), true
	case "bool":
		return jen.Qual(tueImportPath, "PropOf").Call(jen.False()), true
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "rune", "byte":
		return jen.Qual(tueImportPath, "PropOf").Call(jen.Lit(0)), true
	}

	typeCode, ok := renderTypeExpression(valueType)
	if !ok {
		return nil, false
	}
	return jen.Qual(tueImportPath, "PropOf").Call(jen.Op("*").Call(jen.New(typeCode))), true
}

func renderTypeExpression(typ string) (jen.Code, bool) {
	expr, err := goparser.ParseExpr(typ)
	if err != nil {
		return nil, false
	}
	return renderType(expr)
}

func renderType(expr ast.Expr) (jen.Code, bool) {
	switch typed := expr.(type) {
	case *ast.Ident:
		return jen.Id(typed.Name), true
	case *ast.SelectorExpr:
		base, ok := renderType(typed.X)
		if !ok {
			return nil, false
		}
		statement, ok := base.(*jen.Statement)
		if !ok {
			return nil, false
		}
		return statement.Dot(typed.Sel.Name), true
	case *ast.StarExpr:
		base, ok := renderType(typed.X)
		if !ok {
			return nil, false
		}
		return jen.Op("*").Add(base), true
	case *ast.ArrayType:
		element, ok := renderType(typed.Elt)
		if !ok || typed.Len != nil {
			return nil, false
		}
		return jen.Index().Add(element), true
	case *ast.MapType:
		key, ok := renderType(typed.Key)
		if !ok {
			return nil, false
		}
		value, ok := renderType(typed.Value)
		if !ok {
			return nil, false
		}
		return jen.Map(key).Add(value), true
	default:
		return nil, false
	}
}

func assignableType(expected string, actual string) bool {
	expected = normalizeType(expected)
	actual = normalizeType(actual)
	if expected == "" || actual == "" || expected == "unknown" || actual == "unknown" {
		return true
	}
	return expected == actual
}

func normalizeType(typ string) string {
	typ = strings.TrimSpace(typ)
	for strings.HasPrefix(typ, "*") {
		typ = strings.TrimSpace(strings.TrimPrefix(typ, "*"))
	}
	return typ
}

func displayType(typ string) string {
	if typ == "" {
		return "unknown"
	}
	return typ
}

func hasRenderableComponentChildren(children []*gotemplate.Node) bool {
	for _, child := range children {
		if child == nil || child.Kind == gotemplate.NodeComment {
			continue
		}
		if child.Kind == gotemplate.NodeText && strings.TrimSpace(child.Text) == "" {
			continue
		}
		return true
	}
	return false
}

func generatedStem(path string) string {
	base := strings.TrimSuffix(filepath.ToSlash(path), filepath.Ext(path))
	var builder strings.Builder
	lastUnderscore := false
	for _, r := range base {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			builder.WriteRune(r)
			lastUnderscore = false
			continue
		}
		if !lastUnderscore {
			builder.WriteByte('_')
			lastUnderscore = true
		}
	}
	return strings.Trim(builder.String(), "_")
}

func filePath(file File) string {
	if file.Path != "" {
		return file.Path
	}
	if file.Script != nil && file.Script.Path != "" {
		return file.Script.Path
	}
	return ""
}
