package gogen

import (
	"encoding/json"
	"errors"
	"go/format"
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/norunners/vue/internal/compiler/script"
	"github.com/norunners/vue/internal/compiler/sfc"
	templateparser "github.com/norunners/vue/internal/compiler/template"
)

func TestGenerateStaticRenderGolden(t *testing.T) {
	project := generateProject(t, map[string]string{
		"App.tue": `<template>
	<main class="page">Hello {{ name }}</main>
</template>

<script lang="go">
package fixtures

type App struct {
	name string
}
</script>`,
	})
	files := generatedFilesByPath(project)

	wantComponent := `// Code generated by tue; DO NOT EDIT.

package fixtures

type App struct {
	name string
}
`
	if got := string(files["app_tue.go"]); got != wantComponent {
		t.Fatalf("component file =\n%s\nwant =\n%s", got, wantComponent)
	}

	render := string(files["app_render_tue.go"])
	assertContainsInOrder(t, render, []string{
		"package fixtures",
		`import (`,
		`"fmt"`,
		"func NewApp() *vue.Comp {",
		"return vue.CompOf(c, func() vue.VNode {",
		"return appRender(c)",
		"func appRender(c *App) vue.VNode {",
		"return vue.Fragment(",
		"// tue source App.tue",
		"// tue node n1",
		`vue.Element("main", []vue.Attribute{vue.Attr("class", "page")},`,
		`vue.Text("Hello ")`,
		"// tue node n2",
		`vue.Text(fmt.Sprint(c.name))`,
	})
	assertGoParsesAndFormats(t, "app_tue.go", files["app_tue.go"])
	assertGoParsesAndFormats(t, "app_render_tue.go", files["app_render_tue.go"])

	var manifest Manifest
	if err := json.Unmarshal(files["manifest.json"], &manifest); err != nil {
		t.Fatalf("unmarshal manifest: %v", err)
	}
	if manifest.Version != 1 {
		t.Fatalf("manifest version = %d, want 1", manifest.Version)
	}
	if len(manifest.Components) != 1 {
		t.Fatalf("len(manifest.Components) = %d, want 1", len(manifest.Components))
	}
	component := manifest.Components[0]
	if component.Source != "App.tue" || component.Package != "fixtures" || component.Component != "App" || component.Constructor != "NewApp" {
		t.Fatalf("manifest component = %#v, want App fixture metadata", component)
	}
	if strings.Join(component.Generated, ",") != "app_tue.go,app_render_tue.go" {
		t.Fatalf("manifest generated = %#v, want generated file list", component.Generated)
	}
	if len(component.Nodes) != 2 || component.Nodes[0].Kind != "element" || component.Nodes[0].Name != "main" || component.Nodes[1].Kind != "interpolation" {
		t.Fatalf("manifest nodes = %#v, want element and interpolation", component.Nodes)
	}
}

func TestGenerateEscapesStaticTextAndAttributes(t *testing.T) {
	project := generateProject(t, map[string]string{
		"Escaped.tue": `<template>
	<p title="A & B">A & B</p>
</template>

<script lang="go">
package fixtures

type Escaped struct{}
</script>`,
	})
	files := generatedFilesByPath(project)
	render := string(files["escaped_render_tue.go"])
	assertContainsInOrder(t, render, []string{
		`vue.Attr("title", "A & B")`,
		`vue.Text("A & B")`,
	})
}

func TestGenerateNativeEventHandlers(t *testing.T) {
	project := generateProject(t, map[string]string{
		"Button.tue": `<template>
	<button @click="save">Save</button>
	<button @click="cancel()">Cancel</button>
	<button @click="reset">Reset</button>
</template>

<script lang="go">
package fixtures

type Button struct {
	save func()
	cancel func()
}

func (b *Button) reset() {}
</script>`,
	})

	files := generatedFilesByPath(project)
	render := string(files["button_render_tue.go"])
	assertContainsInOrder(t, render, []string{
		`vue.ElementWithEvents("button", nil, []vue.EventBinding{vue.On("click", c.save)},`,
		`vue.Text("Save")`,
		`vue.ElementWithEvents("button", nil, []vue.EventBinding{vue.On("click", func() {`,
		`c.cancel()`,
		`vue.Text("Cancel")`,
		`vue.ElementWithEvents("button", nil, []vue.EventBinding{vue.On("click", c.reset)},`,
		`vue.Text("Reset")`,
	})
	assertGoParsesAndFormats(t, "button_render_tue.go", files["button_render_tue.go"])
}

func TestGenerateRejectsUnsupportedEventHandlerArguments(t *testing.T) {
	_, err := GenerateProject(parseSources(t, map[string]string{
		"Button.tue": `<template>
	<button @click="save(1)">Save</button>
</template>

<script lang="go">
package fixtures

type Button struct {
	save func()
}
</script>`,
	}))
	if err == nil {
		t.Fatal("GenerateProject returned nil error")
	}
	var generateErr *Error
	if !errors.As(err, &generateErr) {
		t.Fatalf("error type = %T, want *Error", err)
	}
	if got, want := generateErr.Error(), `Button.tue:2:18: event handler calls with arguments are not supported in this render slice`; got != want {
		t.Fatalf("error = %q, want %q", got, want)
	}
}

func generateProject(t *testing.T, sources map[string]string) *Project {
	t.Helper()

	project, err := GenerateProject(parseSources(t, sources))
	if err != nil {
		t.Fatalf("GenerateProject returned error: %v", err)
	}
	return project
}

func parseSources(t *testing.T, sources map[string]string) []File {
	t.Helper()

	files := make([]File, 0, len(sources))
	for path, source := range sources {
		parsed, err := sfc.Parse(path, []byte(source))
		if err != nil {
			t.Fatalf("sfc.Parse(%s): %v", path, err)
		}
		tree, err := templateparser.ParseBlock(path, parsed.Template)
		if err != nil {
			t.Fatalf("template.ParseBlock(%s): %v", path, err)
		}
		contract, err := script.ParseBlock(path, parsed.Script)
		if err != nil {
			t.Fatalf("script.ParseBlock(%s): %v", path, err)
		}
		files = append(files, File{
			Path:     path,
			Template: tree,
			Contract: contract,
			Script:   parsed.Script.Content,
		})
	}
	return files
}

func generatedFilesByPath(project *Project) map[string][]byte {
	files := make(map[string][]byte, len(project.Files))
	for _, file := range project.Files {
		files[file.Path] = file.Source
	}
	return files
}

func assertGoParsesAndFormats(t *testing.T, name string, source []byte) {
	t.Helper()

	if _, err := parser.ParseFile(token.NewFileSet(), name, source, parser.AllErrors); err != nil {
		t.Fatalf("parse %s: %v\n%s", name, err, source)
	}
	formatted, err := format.Source(source)
	if err != nil {
		t.Fatalf("format %s: %v", name, err)
	}
	if string(formatted) != string(source) {
		t.Fatalf("%s is not gofmt formatted:\n%s", name, source)
	}
}

func assertContainsInOrder(t *testing.T, source string, fragments []string) {
	t.Helper()

	offset := 0
	for _, fragment := range fragments {
		idx := strings.Index(source[offset:], fragment)
		if idx < 0 {
			t.Fatalf("source does not contain %q after offset %d:\n%s", fragment, offset, source)
		}
		offset += idx + len(fragment)
	}
}
