// Code generated by tue; DO NOT EDIT.

package app

type tueAppContract struct {
	__propName func() (string, bool)
}

func newTueAppContract() tueAppContract {
	return tueAppContract{}
}
func (component *App) NameOk() (string, bool) {
	if component == nil || component.__tue.__propName == nil {
		var zero string
		return zero, false
	}
	value, ok := component.__tue.__propName()
	if ok {
		return value, true
	}
	return value, false
}
func (component *App) Name() string {
	value, _ := component.NameOk()
	return value
}
