// Code generated by tue; DO NOT EDIT.

package app

import tue "github.com/norunners/tue"

type App struct {
	__tue tueAppData
	tue.Comp[struct {
		Name  string `prop:"name"`
		Count int    `state:""`
	}]
}
