// Code generated by tue; DO NOT EDIT.

package app

import "github.com/norunners/tue"

type tueAppData struct {
	__propName   func() (string, bool)
	__stateCount tue.State[int]
}

func newTueAppData() tueAppData {
	return tueAppData{__stateCount: tue.StateOf(*new(int))}
}
func (component *App) NameOk() (string, bool) {
	if component == nil || component.__tue.__propName == nil {
		var zero string
		return zero, false
	}
	value, ok := component.__tue.__propName()
	if ok {
		return value, true
	}
	return value, false
}
func (component *App) Name() string {
	value, _ := component.NameOk()
	return value
}
func (component *App) Count() int {
	if component == nil || component.__tue.__stateCount == nil {
		var zero int
		return zero
	}
	return component.__tue.__stateCount.Get()
}
func (component *App) CountSet(value int) {
	if component == nil || component.__tue.__stateCount == nil {
		return
	}
	component.__tue.__stateCount.Set(value)
}
