// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.CompInstance {
	component := &App{}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", []tue.Attribute{tue.ClassAttr("page", component.themeClass), tue.Attr("data-page", "dashboard")}, []tue.VNode{tue.Element("button", []tue.Attribute{tue.ClassAttr("", (component.kind + "-button"))}, []tue.VNode{tue.Text("Save")}), tue.Element("ul", nil, []tue.VNode{func() tue.VNode {
		__tueItems := component.todos
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for _, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.Element("li", []tue.Attribute{tue.ClassAttr("", __tueItem.className)}, []tue.VNode{tue.Text(fmt.Sprint(__tueItem.text))})
				__tueVNode.Key = fmt.Sprint(__tueItem.id)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}()}), func() tue.VNode {
		if component.visible {
			return tue.Element("section", []tue.Attribute{tue.ClassAttr("panel", component.themeClass)}, []tue.VNode{tue.Text("Ready")})
		}
		return tue.Fragment(nil)
	}()})
}
