// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.Comp {
	component := &App{}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{func() tue.VNode {
		if component.visible {
			return tue.Element("p", nil, []tue.VNode{tue.Text("Visible: "), tue.Text(fmt.Sprint(component.name))})
		}
		return tue.Fragment(nil)
	}(), func() tue.VNode {
		if component.count > 0 {
			return tue.Element("section", nil, []tue.VNode{tue.Element("span", nil, []tue.VNode{tue.Text(fmt.Sprint(component.count))})})
		}
		return tue.Fragment(nil)
	}()})
}
