// Code generated by tue; DO NOT EDIT.

package fixtures

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewCounter() *tue.Comp {
	component := &Counter{}
	return tue.CompOf(component, renderCounter)
}

func renderCounter(component *Counter) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{tue.Element("p", nil, []tue.VNode{tue.Text("Count: "), tue.Text(fmt.Sprint(component.count.Get()))}), tue.ElementWithEvents("button", []tue.Attribute{tue.Attr("type", "button")}, []tue.EventBinding{tue.On("click", component.increment)}, []tue.VNode{tue.Text("Increment")})})
}
