// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.Comp {
	component := &App{}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{tue.Element("ul", nil, []tue.VNode{func() tue.VNode {
		__tueItems := component.todos
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for __tueIndex, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := func() tue.VNode {
					if __tueItem.Done {
						return tue.Element("li", nil, []tue.VNode{tue.Text(fmt.Sprint(__tueIndex)), tue.Text(": "), tue.Text(fmt.Sprint(__tueItem.Text))})
					}
					return tue.Fragment(nil)
				}()
				__tueVNode.Key = fmt.Sprint(__tueItem.ID)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}(), func() tue.VNode {
		__tueItems := component.todos
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for _, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.ElementWithEvents("li", nil, []tue.EventBinding{tue.EventOf("click", component.selectUser)}, []tue.VNode{tue.Text(fmt.Sprint(__tueItem.Text))})
				__tueVNode.Key = fmt.Sprint(__tueItem.ID)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}(), func() tue.VNode {
		__tueItems := component.todosByID
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for __tueIndex, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.Element("li", nil, []tue.VNode{tue.Text(fmt.Sprint(__tueIndex)), tue.Text(": "), tue.Text(fmt.Sprint(__tueItem.Text))})
				__tueVNode.Key = fmt.Sprint(__tueIndex)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}()}), func() tue.VNode {
		__tueItems := component.todos
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for _, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.ComponentWithUpdate("UserBadge", func() *tue.Comp {
					child := &UserBadge{name: tue.PropOfFunc(func() string {
						return __tueItem.Text
					}), active: tue.PropOf(true), onSelect: tue.OnOf(component.selectUser)}
					childComp := tue.CompOf(child, renderUserBadge)
					return childComp
				}, func(childComp *tue.Comp) {
					child := childComp.Component.(*UserBadge)
					child.name = tue.PropOfFunc(func() string {
						return __tueItem.Text
					})
					child.active = tue.PropOf(true)
					child.onSelect = tue.OnOf(component.selectUser)
					childComp.DefaultSlot = nil
				})
				__tueVNode.Key = fmt.Sprint(__tueItem.ID)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}()})
}
