// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.CompInstance {
	component := &App{}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{tue.Element("ul", nil, []tue.VNode{func() tue.VNode {
		__tueItems := component.todos
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for __tueIndex, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := func() tue.VNode {
					if __tueItem.Done {
						return tue.Element("li", nil, []tue.VNode{tue.Text(fmt.Sprint(__tueIndex)), tue.Text(": "), tue.Text(fmt.Sprint(__tueItem.Text))})
					}
					return tue.Fragment(nil)
				}()
				__tueVNode.Key = fmt.Sprint(__tueItem.ID)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}(), func() tue.VNode {
		__tueItems := component.todos
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for _, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.ElementWithEvents("li", nil, []tue.EventBinding{tue.EventOf("click", component.selectUser)}, []tue.VNode{tue.Text(fmt.Sprint(__tueItem.Text))})
				__tueVNode.Key = fmt.Sprint(__tueItem.ID)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}(), func() tue.VNode {
		__tueItems := component.todosByID
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for __tueIndex, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.Element("li", nil, []tue.VNode{tue.Text(fmt.Sprint(__tueIndex)), tue.Text(": "), tue.Text(fmt.Sprint(__tueItem.Text))})
				__tueVNode.Key = fmt.Sprint(__tueIndex)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}()}), func() tue.VNode {
		__tueItems := component.todos
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for _, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.ComponentWithUpdate("UserBadge", func() *tue.CompInstance {
					child := &UserBadge{__tue: newTueUserBadgeData()}
					child.__tue.__propName = func() (string, bool) {
						return __tueItem.Text, true
					}
					child.__tue.__propActive = func() (bool, bool) {
						return true, true
					}
					child.__tue.__eventSelect = component.selectUser
					childComp := tue.CompOf(child, renderUserBadge)
					return childComp
				}, func(childComp *tue.CompInstance) {
					child := childComp.Component.(*UserBadge)
					child.__tue.__propName = func() (string, bool) {
						return __tueItem.Text, true
					}
					child.__tue.__propActive = func() (bool, bool) {
						return true, true
					}
					child.__tue.__eventSelect = component.selectUser
					childComp.DefaultSlot = nil
				})
				__tueVNode.Key = fmt.Sprint(__tueItem.ID)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}()})
}
