// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.CompInstance {
	component := &App{__tue: newTueAppData()}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{tue.ElementWithEvents("input", []tue.Attribute{tue.Attr("value", component.Query())}, []tue.EventBinding{tue.OnValue("input", func(value string) {
		component.QuerySet(value)
	}), tue.EventOf("input", component.touch)}, nil), tue.ElementWithEvents("input", []tue.Attribute{tue.Attr("type", "checkbox"), tue.BoolStateAttr("checked", component.Enabled())}, []tue.EventBinding{tue.OnChecked("change", func(checked bool) {
		component.EnabledSet(checked)
	})}, nil), tue.ElementWithEvents("select", []tue.Attribute{tue.Attr("value", component.Choice())}, []tue.EventBinding{tue.OnValue("change", func(value string) {
		component.ChoiceSet(value)
	})}, []tue.VNode{tue.Element("option", []tue.Attribute{tue.Attr("value", "small")}, []tue.VNode{tue.Text("Small")}), tue.Element("option", []tue.Attribute{tue.Attr("value", "large")}, []tue.VNode{tue.Text("Large")})}), tue.Element("p", nil, []tue.VNode{tue.Text(fmt.Sprint(component.Query())), tue.Text(fmt.Sprint(component.Enabled())), tue.Text(fmt.Sprint(component.Choice()))})})
}
