// Code generated by tue; DO NOT EDIT.

package fixtures

import "github.com/norunners/tue"

func NewParent() *tue.CompInstance {
	component := &Parent{__tue: newTueParentData()}
	return tue.CompOf(component, renderParent)
}

func renderParent(component *Parent) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{func() tue.VNode {
		if component.ShowBadge() {
			return tue.ComponentWithUpdate("UserBadge", func() *tue.CompInstance {
				child := &UserBadge{__tue: newTueUserBadgeData()}
				child.__tue.__propName = func() (string, bool) {
					return component.Name(), true
				}
				child.__tue.__propActive = func() (bool, bool) {
					return true, true
				}
				child.__tue.__propSubtitle = nil
				child.__tue.__eventSelect = component.selectUser
				child.__tue.__eventRange = component.selectRange
				child.__tue.__eventTags = component.selectTags
				child.__tue.__eventDismiss = nil
				childComp := tue.CompOf(child, renderUserBadge, func() {
					child.__tue.__computedLabel = tue.ComputedOfFunc(child.label)
				})
				return childComp
			}, func(childComp *tue.CompInstance) {
				child := childComp.Component.(*UserBadge)
				child.__tue.__propName = func() (string, bool) {
					return component.Name(), true
				}
				child.__tue.__propActive = func() (bool, bool) {
					return true, true
				}
				child.__tue.__propSubtitle = nil
				child.__tue.__eventSelect = component.selectUser
				child.__tue.__eventRange = component.selectRange
				child.__tue.__eventTags = component.selectTags
				child.__tue.__eventDismiss = nil
				childComp.DefaultSlot = nil
			})
		}
		return tue.Fragment(nil)
	}()})
}
