// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.CompInstance {
	component := &App{}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", []tue.Attribute{tue.Attr("class", "page"), tue.BoolAttr("data-tue-c-d8d60a14")}, []tue.VNode{tue.WithScopeAttrs(tue.ComponentWithUpdate("Banner", func() *tue.CompInstance {
		child := &Banner{}
		childComp := tue.CompOf(child, renderBanner)
		return childComp
	}, func(childComp *tue.CompInstance) {
		childComp.DefaultSlot = nil
	}), "data-tue-c-d8d60a14"), tue.Element("section", []tue.Attribute{tue.Attr("class", "card"), tue.BoolAttr("data-tue-c-d8d60a14")}, []tue.VNode{tue.Element("h1", []tue.Attribute{tue.BoolAttr("data-tue-c-d8d60a14")}, []tue.VNode{tue.Text(fmt.Sprint(component.title))})}), func() tue.VNode {
		if component.enabled {
			return tue.Element("button", []tue.Attribute{tue.BoolAttr("data-tue-c-d8d60a14")}, []tue.VNode{tue.Text("Save")})
		}
		return tue.Fragment(nil)
	}(), tue.Element("ul", []tue.Attribute{tue.BoolAttr("data-tue-c-d8d60a14")}, []tue.VNode{func() tue.VNode {
		__tueItems := component.items
		__tueNodes := make([]tue.VNode, 0, len(__tueItems))
		for _, __tueItem := range __tueItems {
			__tueNodes = append(__tueNodes, func() tue.VNode {
				__tueVNode := tue.Element("li", []tue.Attribute{tue.BoolAttr("data-tue-c-d8d60a14")}, []tue.VNode{tue.Text(fmt.Sprint(__tueItem.text))})
				__tueVNode.Key = fmt.Sprint(__tueItem.id)
				return __tueVNode
			}())
		}
		return tue.Fragment(__tueNodes)
	}()})})
}
