// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.Comp {
	component := &App{}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{tue.ComponentWithUpdate("Card", func() *tue.Comp {
		child := &Card{title: tue.PropOf("Status")}
		childComp := tue.CompOf(child, renderCard)
		childComp.DefaultSlot = func() tue.VNode {
			return tue.Fragment([]tue.VNode{tue.Element("p", []tue.Attribute{tue.Attr("class", "body")}, []tue.VNode{tue.Text(fmt.Sprint(component.message))}), func() tue.VNode {
				if component.ready {
					return tue.Element("span", nil, []tue.VNode{tue.Text("Ready")})
				}
				return tue.Fragment(nil)
			}()})
		}
		return childComp
	}, func(childComp *tue.Comp) {
		child := childComp.Component.(*Card)
		child.title = tue.PropOf("Status")
		childComp.DefaultSlot = func() tue.VNode {
			return tue.Fragment([]tue.VNode{tue.Element("p", []tue.Attribute{tue.Attr("class", "body")}, []tue.VNode{tue.Text(fmt.Sprint(component.message))}), func() tue.VNode {
				if component.ready {
					return tue.Element("span", nil, []tue.VNode{tue.Text("Ready")})
				}
				return tue.Fragment(nil)
			}()})
		}
	}), tue.ComponentWithUpdate("Card", func() *tue.Comp {
		child := &Card{title: tue.PropOf("Empty")}
		childComp := tue.CompOf(child, renderCard)
		return childComp
	}, func(childComp *tue.Comp) {
		child := childComp.Component.(*Card)
		child.title = tue.PropOf("Empty")
		childComp.DefaultSlot = nil
	})})
}
