// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewApp() *tue.CompInstance {
	component := &App{}
	return tue.CompOf(component, renderApp)
}

func renderApp(component *App) tue.VNode {
	return tue.Element("main", nil, []tue.VNode{tue.ComponentWithUpdate("Card", func() *tue.CompInstance {
		child := &Card{__tue: newTueCardData()}
		child.__tue.__propTitle = func() (string, bool) {
			return "Status", true
		}
		childComp := tue.CompOf(child, renderCard)
		childComp.DefaultSlot = func() tue.VNode {
			return tue.Fragment([]tue.VNode{tue.Element("p", []tue.Attribute{tue.Attr("class", "body")}, []tue.VNode{tue.Text(fmt.Sprint(component.message))}), func() tue.VNode {
				if component.ready {
					return tue.Element("span", nil, []tue.VNode{tue.Text("Ready")})
				}
				return tue.Fragment(nil)
			}()})
		}
		return childComp
	}, func(childComp *tue.CompInstance) {
		child := childComp.Component.(*Card)
		child.__tue.__propTitle = func() (string, bool) {
			return "Status", true
		}
		if child.__tue.__inputVersion != nil {
			child.__tue.__inputVersion.Set(child.__tue.__inputVersion.Get() + 1)
		}
		childComp.DefaultSlot = func() tue.VNode {
			return tue.Fragment([]tue.VNode{tue.Element("p", []tue.Attribute{tue.Attr("class", "body")}, []tue.VNode{tue.Text(fmt.Sprint(component.message))}), func() tue.VNode {
				if component.ready {
					return tue.Element("span", nil, []tue.VNode{tue.Text("Ready")})
				}
				return tue.Fragment(nil)
			}()})
		}
	}), tue.ComponentWithUpdate("Card", func() *tue.CompInstance {
		child := &Card{__tue: newTueCardData()}
		child.__tue.__propTitle = func() (string, bool) {
			return "Empty", true
		}
		childComp := tue.CompOf(child, renderCard)
		return childComp
	}, func(childComp *tue.CompInstance) {
		child := childComp.Component.(*Card)
		child.__tue.__propTitle = func() (string, bool) {
			return "Empty", true
		}
		if child.__tue.__inputVersion != nil {
			child.__tue.__inputVersion.Set(child.__tue.__inputVersion.Get() + 1)
		}
		childComp.DefaultSlot = nil
	})})
}
