// Code generated by tue; DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/norunners/tue"
)

func NewCard() *tue.Comp {
	component := &Card{}
	return tue.CompOf(component, renderCard)
}

func renderCard(component *Card) tue.VNode {
	return tue.Element("section", []tue.Attribute{tue.Attr("class", "card")}, []tue.VNode{tue.Element("h2", nil, []tue.VNode{tue.Text(fmt.Sprint(component.title.Get()))}), tue.Slot(tue.Element("p", nil, []tue.VNode{tue.Text("Fallback")}))})
}
