// Code generated by tue; DO NOT EDIT.

package fixtures

import "github.com/norunners/tue"

type tueUserBadgeData struct {
	__propName              func() (string, bool)
	__propActive            func() (bool, bool)
	__propSubtitle          func() (string, bool)
	__inputVersion          tue.State[int]
	__eventSelect           func(value string)
	__eventRange            func(value1 string, value2 int)
	__eventTags             func(value []string)
	__eventDismiss          func(value string)
	__stateExpanded         tue.State[bool]
	__stateInitialLabel     tue.State[string]
	__computedLabel         tue.Computed[string]
	__computedSubtitleLabel tue.Computed[string]
}

func newTueUserBadgeData() tueUserBadgeData {
	return tueUserBadgeData{__inputVersion: tue.StateOf(0), __stateExpanded: tue.StateOf(*new(bool)), __stateInitialLabel: tue.StateOf(*new(string))}
}
func (component *UserBadge) NameOk() (string, bool) {
	if component == nil {
		var zero string
		return zero, false
	}
	if component.__tue.__inputVersion != nil {
		_ = component.__tue.__inputVersion.Get()
	}
	if component.__tue.__propName == nil {
		var zero string
		return zero, false
	}
	value, ok := component.__tue.__propName()
	if ok {
		return value, true
	}
	return value, false
}
func (component *UserBadge) Name() string {
	value, _ := component.NameOk()
	return value
}
func (component *UserBadge) ActiveOk() (bool, bool) {
	if component == nil {
		var zero bool
		return zero, false
	}
	if component.__tue.__inputVersion != nil {
		_ = component.__tue.__inputVersion.Get()
	}
	if component.__tue.__propActive == nil {
		var zero bool
		return zero, false
	}
	value, ok := component.__tue.__propActive()
	if ok {
		return value, true
	}
	return value, false
}
func (component *UserBadge) Active() bool {
	value, _ := component.ActiveOk()
	return value
}
func (component *UserBadge) SubtitleOk() (string, bool) {
	if component == nil {
		var zero string
		return zero, false
	}
	if component.__tue.__inputVersion != nil {
		_ = component.__tue.__inputVersion.Get()
	}
	if component.__tue.__propSubtitle == nil {
		var zero string
		return zero, false
	}
	value, ok := component.__tue.__propSubtitle()
	if ok {
		return value, true
	}
	return value, false
}
func (component *UserBadge) Subtitle() string {
	value, _ := component.SubtitleOk()
	return value
}
func (component *UserBadge) Select(value string) bool {
	if component == nil || component.__tue.__eventSelect == nil {
		return false
	}
	component.__tue.__eventSelect(value)
	return true
}
func (component *UserBadge) Range(value1 string, value2 int) bool {
	if component == nil || component.__tue.__eventRange == nil {
		return false
	}
	component.__tue.__eventRange(value1, value2)
	return true
}
func (component *UserBadge) Tags(value []string) bool {
	if component == nil || component.__tue.__eventTags == nil {
		return false
	}
	component.__tue.__eventTags(value)
	return true
}
func (component *UserBadge) Dismiss(value string) bool {
	if component == nil || component.__tue.__eventDismiss == nil {
		return false
	}
	component.__tue.__eventDismiss(value)
	return true
}
func (component *UserBadge) Expanded() bool {
	if component == nil || component.__tue.__stateExpanded == nil {
		var zero bool
		return zero
	}
	return component.__tue.__stateExpanded.Get()
}
func (component *UserBadge) ExpandedSet(value bool) {
	if component == nil || component.__tue.__stateExpanded == nil {
		return
	}
	component.__tue.__stateExpanded.Set(value)
}
func (component *UserBadge) InitialLabel() string {
	if component == nil || component.__tue.__stateInitialLabel == nil {
		var zero string
		return zero
	}
	return component.__tue.__stateInitialLabel.Get()
}
func (component *UserBadge) InitialLabelSet(value string) {
	if component == nil || component.__tue.__stateInitialLabel == nil {
		return
	}
	component.__tue.__stateInitialLabel.Set(value)
}
func (component *UserBadge) Label() string {
	if component == nil || component.__tue.__computedLabel == nil {
		var zero string
		return zero
	}
	return component.__tue.__computedLabel.Get()
}
func (component *UserBadge) SubtitleLabel() string {
	if component == nil || component.__tue.__computedSubtitleLabel == nil {
		var zero string
		return zero
	}
	return component.__tue.__computedSubtitleLabel.Get()
}
