// Code generated by tue; DO NOT EDIT.

package fixtures

import "github.com/norunners/tue"

type tueUserBadgeData struct {
	__propName      func() (string, bool)
	__propActive    func() (bool, bool)
	__propLabel     func() (string, bool)
	__eventSelect   func(value string)
	__eventRange    func(value1 string, value2 int)
	__eventTags     func(value []string)
	__eventDismiss  func(value string)
	__stateExpanded tue.State[bool]
}

func newTueUserBadgeData() tueUserBadgeData {
	return tueUserBadgeData{__stateExpanded: tue.StateOf(*new(bool))}
}
func (component *UserBadge) NameOk() (string, bool) {
	if component == nil || component.__tue.__propName == nil {
		var zero string
		return zero, false
	}
	value, ok := component.__tue.__propName()
	if ok {
		return value, true
	}
	return value, false
}
func (component *UserBadge) Name() string {
	value, _ := component.NameOk()
	return value
}
func (component *UserBadge) ActiveOk() (bool, bool) {
	if component == nil || component.__tue.__propActive == nil {
		var zero bool
		return zero, false
	}
	value, ok := component.__tue.__propActive()
	if ok {
		return value, true
	}
	return value, false
}
func (component *UserBadge) Active() bool {
	value, _ := component.ActiveOk()
	return value
}
func (component *UserBadge) LabelOk() (string, bool) {
	if component == nil || component.__tue.__propLabel == nil {
		var zero string
		return zero, false
	}
	value, ok := component.__tue.__propLabel()
	if ok {
		return value, true
	}
	return value, false
}
func (component *UserBadge) Label() string {
	value, _ := component.LabelOk()
	return value
}
func (component *UserBadge) Select(value string) bool {
	if component == nil || component.__tue.__eventSelect == nil {
		return false
	}
	component.__tue.__eventSelect(value)
	return true
}
func (component *UserBadge) Range(value1 string, value2 int) bool {
	if component == nil || component.__tue.__eventRange == nil {
		return false
	}
	component.__tue.__eventRange(value1, value2)
	return true
}
func (component *UserBadge) Tags(value []string) bool {
	if component == nil || component.__tue.__eventTags == nil {
		return false
	}
	component.__tue.__eventTags(value)
	return true
}
func (component *UserBadge) Dismiss(value string) bool {
	if component == nil || component.__tue.__eventDismiss == nil {
		return false
	}
	component.__tue.__eventDismiss(value)
	return true
}
func (component *UserBadge) Expanded() bool {
	if component == nil || component.__tue.__stateExpanded == nil {
		var zero bool
		return zero
	}
	return component.__tue.__stateExpanded.Get()
}
func (component *UserBadge) ExpandedSet(value bool) {
	if component == nil || component.__tue.__stateExpanded == nil {
		return
	}
	component.__tue.__stateExpanded.Set(value)
}
